INSERT INTO customer (id, name, email, endereco, endereco2, endereco3) VALUES
(1, 'Mariazinha', 'mariazinha@email.com','Rua teste1, 1212','',''),
(2, 'Joãozinho', 'joaozinho@email.com','Rua teste2, 1213','',''),
(3, 'Joãozinho', 'joaozinho@email.com','Rua teste3, 1214','',''),
(4, 'Joãozinho', 'joaozinho@email.com','','',''),
(5, 'Joãozinho', 'joaozinho@email.com','','',''),
(6, 'Joãozinho', 'joaozinho@email.com','','',''),
(7, 'Joãozinho', 'joaozinho@email.com','','',''),
(8, 'Joãozinho', 'joaozinho@email.com','','',''),
(9, 'Joãozinho', 'joaozinho@email.com','','',''),
(10, 'Joãozinho', 'joaozinho@email.com','','',''),
(11, 'Joãozinho', 'joaozinho@email.com','','',''),
(12, 'Joãozinho', 'joaozinho@email.com','','',''),
(13, 'Joãozinho', 'joaozinho@email.com','','',''),
(14, 'Joãozinho', 'joaozinho@email.com','','',''),
(15, 'Joãozinho', 'joaozinho@email.com','','',''),
(16, 'Joãozinho', 'joaozinho@email.com','','',''),
(17, 'Joãozinho', 'joaozinho@email.com','','',''),
(18, 'Joãozinho', 'joaozinho@email.com','','',''),
(19, 'Joãozinho', 'joaozinho@email.com','','',''),
(20, 'Joãozinho', 'joaozinho@email.com','','',''),
(21, 'Joãozinho', 'joaozinho@email.com','','','');
